#
# Copyright © 2005 - 2021 Schlichtherle IT Services.
# All rights reserved. Use is subject to license terms.
#
---
cache:
  directories:
    - project/.boot
    - project/.coursier
    - project/.ivy
    - project/.sbtboot

dist: focal

# Don't use -slim or -alpine image tags here - the SBT Wrapper runs a shell script which wouldn't always work then:
env:
  - COMPILE_IMAGE_TAG=8-jdk TEST_IMAGE_TAG=8-jdk
  - COMPILE_IMAGE_TAG=11-jdk TEST_IMAGE_TAG=15-jdk

install: ./docker-sbtx $COMPILE_IMAGE_TAG -batch +test:compile

language: minimal

# Run the build in Docker to protect it from changes in the environment:
services:
  - docker

script: ./docker-sbtx $TEST_IMAGE_TAG -batch +test
